### ISSUE TITLE
[Package Request] Amneziawg-go

### ISSUE THREAD

**Issue by mezhgano** [Entware/Entware#1078]
**Describe the solution you'd like**
AmneziaWG is a contemporary version of the WireGuard protocol. It's a fork of WireGuard-Go and offers protection against detection by Deep Packet Inspection (DPI) systems. At the same time, it retains the simplified architecture and high performance of the original.

The precursor, WireGuard, is known for its efficiency but had issues with detection due to its distinctive packet signatures. AmneziaWG addresses this problem by employing advanced obfuscation methods, allowing its traffic to blend seamlessly with regular internet traffic. As a result, AmneziaWG maintains high performance while adding an extra layer of stealth, making it a superb choice for those seeking a fast and discreet VPN connection.

https://github.com/amnezia-vpn/amneziawg-go

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by zyxmon** [comment]
http://zyxnerd.zyxmon.org/files/amneziawg-tools_1.0.20240213-1_mipsel-3.4.ipk
http://zyxnerd.zyxmon.org/files/amneziawg-go_v0.2.12-1_mipsel-3.4.ipk

Please give more info on usage if the packages are OK

**Comment by mezhgano** [comment]
Wow, thanks for such a quick reply
Sorry, i misunderstood last task, i doesn't have **mipselsf** device to test this, only **armv7sf**...
It is possible to adopt package from mipsel to arm without to much effort?
Anyway, will post link to this issue to Russian forum right now, for someone who own mipsel device to test it.

**Comment by zyxmon** [comment]
http://zyxnerd.zyxmon.org/files/amneziawg-tools_1.0.20240213-1_armv7-3.2.ipk
и
http://zyxnerd.zyxmon.org/files/amneziawg-go_nohf_v0.2.12-1_armv7-3.2.ipk
или
http://zyxnerd.zyxmon.org/files/amneziawg-go_v0.2.12-1_armv7-3.2.ipk

Когда то давно, я проверял userspace вариант обычного wg используя это материал - https://lowendtalk.com/discussion/comment/3073060 (не думаю, что что0то сильно поменялось, кроме добавленных опций амнезии).

**Comment by JkktBkkt** [comment]
> http://zyxnerd.zyxmon.org/files/amneziawg-tools_1.0.20240213-1_mipsel-3.4.ipk http://zyxnerd.zyxmon.org/files/amneziawg-go_v0.2.12-1_mipsel-3.4.ipk

I tried building these myself, and got the same error for the amneziawg-go one as the ones you provided produce.
Can't test much of the tools one without the -go one creating an interface first (though the generic stuff like generating keys works, and the errors on no tunnel provided for other commands do look correct too), and that's where it fails on my system, creating the tunnel.

<details>
  <summary># amneziawg-go awg0</summary>

```
┌──────────────────────────────────────────────────────────────┐
│                                                              │
│       Running amneziawg-go is not required because this      │
│       kernel has first class support for AmneziaWG. For      │
│       information on installing the kernel module,           │
│       please visit:                                          │
| https://github.com/amnezia-vpn/amneziawg-linux-kernel-module │
│                                                              │
└──────────────────────────────────────────────────────────────┘
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x17108c]

goroutine 1 [running]:
github.com/amnezia-vpn/amneziawg-go/tun.(*NativeTun).initFromFlags.func1(0x3)
        github.com/amnezia-vpn/amneziawg-go/tun/tun_linux.go:536 +0x23c
internal/poll.(*FD).RawControl(0x442100, 0x466018)
        internal/poll/fd_posix.go:61 +0x10c
os.(*rawConn).Control(0x41e0a8, 0x466018)
        os/rawconn.go:22 +0x9c
github.com/amnezia-vpn/amneziawg-go/tun.(*NativeTun).initFromFlags(0x656000, {0x40c110, 0x4})
        github.com/amnezia-vpn/amneziawg-go/tun/tun_linux.go:516 +0x1d4
github.com/amnezia-vpn/amneziawg-go/tun.CreateTUNFromFile(0x41e090, 0x58c)
        github.com/amnezia-vpn/amneziawg-go/tun/tun_linux.go:601 +0x4bc
github.com/amnezia-vpn/amneziawg-go/tun.CreateTUN({0x7ff45d68, 0x4}, 0x58c)
        github.com/amnezia-vpn/amneziawg-go/tun/tun_linux.go:581 +0x260
main.main.func2(0x46ef1c)
        github.com/amnezia-vpn/amneziawg-go/main.go:117 +0x17c
main.main()
        github.com/amnezia-vpn/amneziawg-go/main.go:134 +0x3e4
```
System is:
Linux rtac66ua1 4.4.302-rt232-st52 #32634 Fri Aug 23 05:27:36 +07 2024 mips DD-WRT
I double-checked that this is the correct binary for my device, against binary /sbin/rc which is providing nvram command
</details>

```
/sbin/rc: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-mipsel-sf.so.1, no section header
/opt/bin/awg: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /opt/lib/ld.so.1, for GNU/Linux 3.2.0, stripped
/opt/bin/amneziawg-go: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, stripped
```
The only missing part is rel2, but for sanity check I installed wireguard-go which identifies as the same via file and runs properly.

**Comment by zyxmon** [comment]
ip-full package is a missing dependency! Please install. On my mipsel device amneziawg-go creates wg0 interface:

root@Keenetic_Ultra:/opt/tmp$ ./amneziawg-go wg0
┌──────────────────────────────────────────────────────────────┐
│                                                              │
│       Running amneziawg-go is not required because this      │
│       kernel has first class support for AmneziaWG. For      │
│       information on installing the kernel module,           │
│       please visit:                                          │
| https://github.com/amnezia-vpn/amneziawg-linux-kernel-module │
│                                                              │
└──────────────────────────────────────────────────────────────┘
root@Keenetic_Ultra:/opt/tmp$ ip a

39: wg0: <POINTOPOINT,MULTICAST,NOARP> mtu 1420 qdisc noop state DOWN group default qlen 500
    link/none
root@Keenetic_Ultra:/opt/tmp$ uname -a
Linux Keenetic_Ultra 4.9-ndm-5 #0 SMP Thu Jun 6 13:52:52 2024 mips GNU/Linux
....

**Comment by JkktBkkt** [comment]
Package ip-full (4.4.0-10b) installed in root is up to date.
and ip a provides output that looks correct, but it doesn't have the awg-created device (because awg crashes)
I do notice the 4.4 vs 4.9 difference in kernels though, wondering now if that could be the culprit. But I don't think I'd be able to do anything about that, with the firmware being taken from ddwrt.. Possibly could build it myself but I'd much rather not have to delve into that.
Any other suggestions?

**Comment by zyxmon** [comment]
@JkktBkkt - make an issue here - https://github.com/amnezia-vpn/amneziawg-go/issues

**Comment by JkktBkkt** [comment]
Unfortunately that's basically pointless. They've removed the sections about freebsd and arm after forking, indicating that in these people are on their own and those configurations are not supported. Frankly, it's obvious that such architectures as mips aren't their priority.

**Comment by zyxmon** [comment]
I've test it on my mipsel router and it works. log is here - https://forum.keenetic.com/topic/18794-amneziawg-go-для-entware/

**Comment by mezhgano** [comment]
Только сейчас выдался момент протестировать, роутер ASUS RT-AX56U, если правильно понимаю, не ставиться из-за слишком старой версии архитектуры роутера...

```bash
$ opkg install amneziawg-go_nohf_v0.2.12-1_armv7-3.2.ipk
Unknown package 'amneziawg-go_nohf'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for amneziawg-go_nohf found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package amneziawg-go_nohf.
```

```bash
$ opkg print-architecture
arch all 100
arch armv7-2.6 160
```

P.S. Не знаю, может просто попробовать изменить требования к архитектуре в файле `control` ipk пакета, вдруг получиться... 🤔
