### ISSUE TITLE
syncthing: fails to start after reboot or resume (wol)

### ISSUE THREAD

**Issue by blshkv** [Entware/Entware#1118]
DS1621+

https://pkg.entware.net/binaries/x86-64/Packages.html
https://bin.entware.net/x64-k3.2/

Processor:    AMD Ryzen Embedded V1500B
Architecture: x86_64

/var/log/esynoscheduler.log:
```bash
(13618) esynoscheduler_lib.cpp:112 remove status, pid=14058
(13618) esynoscheduler_lib.cpp:734 unlink /tmp/esynoscheduler.script.13618
(13618) esynoscheduler_lib.cpp:739 unlink /volume2/@tmp/esynoscheduler.output.14058
Mon Dec 23 09:01:05 CST 2024
fire bootup event
(13573) esynoscheduler_lib.cpp:1219 not config file exist, path=/usr/syno/etc/esynoscheduler/esynoscheduler-conf.json
(13573) esynoscheduler_lib.cpp:1219 not config file exist, path=/usr/syno/etc/esynoscheduler/esynoscheduler-conf.json
(13573) util.cpp:323 no config file exist, path=/usr/syno/etc/esynoscheduler/esynoscheduler-conf.json
(13573) esynoscheduler_lib.cpp:684 jTaskArray size=1
(13573) esynoscheduler_lib.cpp:474 task=Entware, strOp=#!/bin/sh

# Mount/Start Entware
mkdir -p /opt
mount -o bind "/volume1/@Entware/opt" /opt
/opt/etc/init.d/rc.unslung start

# Add Entware Profile in Global Profile
if grep  -qF  '/opt/etc/profile' /etc/profile; then
        echo "Confirmed: Entware Profile in Global Profile"
else
        echo "Adding: Entware Profile in Global Profile"
cat >> /etc/profile <<"EOF"

# Load Entware Profile
. /opt/etc/profile
EOF
fi

# Update Entware List
#/opt/bin/opkg update
(13573) esynoscheduler_lib.cpp:224 not set output path
(13573) esynoscheduler_lib.cpp:257 script path=/tmp/esynoscheduler.script.13573
(13573) esynoscheduler_lib.cpp:503 strOutPath=/volume2/@tmp/esynoscheduler.output
.[1;37m Starting transmission-daemon... .[m            .[1;32m done. .[m
.[1;37m Starting syncthing... .[m            .[1;31m failed. .[m
Confirmed: Entware Profile in Global Profile
(14255) esynoscheduler_lib.cpp:511 fork and run task=Entware
(14255) esynoscheduler_lib.cpp:522 run script=#!/bin/sh

```

also, there is the following error when I check the status:
```bash
root@nas:~# /opt/etc/init.d/S92syncthing check
 Checking syncthing...              dead.
```

**Comment by blshkv** [comment]
I redirected output of /opt/etc/init.d/rc.func to a file, got the following error:
```
$HOME is not defined
panic: Failed to get user home dir

goroutine 1 [running]:
github.com/syncthing/syncthing/lib/locations.userHomeDir()
        github.com/syncthing/syncthing/lib/locations/locations.go:279 +0x78
github.com/syncthing/syncthing/lib/locations.init.0()
        github.com/syncthing/syncthing/lib/locations/locations.go:59 +0x17
```

**Comment by ryzhovau** [comment]
Can't reproduce it. Looks like something environment specific.

**Comment by blshkv** [comment]
This is clearly NOT what I expected. I have a standard Synology NAS with Entware installed using recommended steps, and I don't see how it could be "environment specific".
So if you don't have it or can't reproduce it, it doesn't mean that the issue is unique.

Anyway, here is a patch to fix this problem:
```
--- S92syncthing.orig   2025-01-11 01:04:19.000000000 +0800
+++ S92syncthing        2025-06-11 09:24:20.655775241 +0800
@@ -7,6 +7,8 @@
    sed -i 's|127\.0\.0\.1|0.0.0.0|' /opt/etc/syncthing/config.xml
 fi
 
+export HOME="/root"
+
 ENABLED=yes
 PROCS=syncthing
 ARGS="serve"
```

Hopefully, it would give you a clue about the root cause.

**Comment by Turbid** [comment]
I confirm this bug for QNAP TS-469L and the fix above.
