### ISSUE TITLE
python 2.7  giving errors when starting deluge daemon 

### ISSUE THREAD

**Issue by AbuYahyaa** [Entware/Entware#202]
There is an issue with one of the python2.7 json files. kindly take a look  

```
starting deluged
~ # [ERROR   ] 02:23:21 config:390 Expecting : delimiter: line 8 column 24 (char 138)
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/deluge/config.py", line 388, in load
    self.__config.update(json.loads(data[start:end]))
  File "/opt/lib/python2.7/json/__init__.py", line 339, in loads
  File "/opt/lib/python2.7/json/decoder.py", line 364, in decode
  File "/opt/lib/python2.7/json/decoder.py", line 380, in raw_decode
ValueError: Expecting : delimiter: line 8 column 24 (char 138)

`

on stopping deluge

[ERROR   ] 02:40:04 component:149 [Failure instance: Traceback: <type 'exceptions.ValueError'>: Expecting : delimiter: line 8 column 24 (char 138)
/opt/lib/python2.7/site-packages/deluge/core/daemon.py:197:_shutdown
/opt/lib/python2.7/site-packages/deluge/component.py:392:shutdown
/opt/lib/python2.7/site-packages/deluge/component.py:202:_component_shutdown
/opt/lib/python2.7/site-packages/deluge/component.py:155:_component_stop
--- <exception caught here> ---
/opt/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
/opt/lib/python2.7/site-packages/deluge/core/core.py:177:stop
/opt/lib/python2.7/site-packages/deluge/config.py:416:save
/opt/lib/python2.7/json/__init__.py:339:loads
/opt/lib/python2.7/json/decoder.py:364:decode
/opt/lib/python2.7/json/decoder.py:380:raw_decode
]
```

**Comment by zyxmon** [comment]
Not reproduced. Please update your packages.

```
root # /opt/etc/init.d/S80deluged start
starting deluged
root # ps | grep deluge
23420 root     99.2m S    {deluged} /opt/bin/python2.7 /opt/bin/deluged
23450 root      4380 S    grep deluge
root # /opt/etc/init.d/S80deluged stop
stopping deluged
root # ps | grep deluge
23929 root      4380 S    grep deluge
```
