### ISSUE TITLE
go_nohf fails with runtime error on compile

### ISSUE THREAD

**Issue by VA1DER** [Entware/Entware#622]
**Describe the bug**
[go_nohf]: Go compiles fail with a runtime error on compile on go_hohf on Entware armv7sf-k3.2.  This is at the very beginning of a compile of syncthing.  Interestingly, the entire compile succeeds on identical hardware on Entware armv7sf-k2.6.

The first failure message received suggests that somewhere in the toolchain something is not compiled without hardware float.

**Environment (please complete the following information):**
 - Entware feed: armv7sf-k3.2
 - Device: Netgear R7000
 - Firmware version: DD-WRT v3.0-r44863, kernel 4.4.245

The entire syncthing compile succeeds using go_nohf in the following environment:
 - Entware feed: armv7sf-k2.6
 - Device: Netgear R7000
 - Firmware version: Fresh Tomato 2021.1, kernel 2.6.36.4

First failure message:
```
go tool compile: exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0x8bec4]

goroutine 1 [running]:
strconv.adjustLastDigit(0xb946d0, 0x76f06088, 0x0, 0x1d, 0x562c4, 0xb96de0, 0x1044034, 0x102478c, 0x12, 0x562c4, ...)
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/strconv/extfloat.go:654 +0x1fc

```

Subsequent failure messages:
```
go tool compile: exit status 2
runtime: unexpected return pc for runtime.doInit called from 0x0
stack: frame={sp:0x1035f74, fp:0x1035f88} stack=[0x1034000,0x1036000)
01035ef4:  010000e0  0005d570 <runtime.sigpanic+796>  01035f58  01035f44 
01035f04:  0101a360  0100c19c  0001d6a8 <runtime.makemap_small+28>  9cf687f4 
01035f14:  00790820  00000001  0100a400  0101a365 
01035f24:  010000e0  0100a400  0101a360  00056300 <runtime.doInit+136> 
01035f34:  00768890  010000f0  00000000  00770b28 
01035f44:  00bb06b8  00000000  00000000  00000000 
01035f54:  00000000  000562d0 <runtime.doInit+88>  00770b28  00bb06b8 
01035f64:  00000003  000562c4 <runtime.doInit+76>  010000e0  00056300 <runtime.doInit+136> 
01035f74: <00000000  0000001e  000562c4 <runtime.doInit+76>  00b96de0 
01035f84:  01044034 >0102478c  00000012  000562c4 <runtime.doInit+76> 
01035f94:  00b972e0  00048e00 <runtime.main+296>  00000040  00000000 
01035fa4:  00048e94 <runtime.main+444>  00b93f08  00000000  00765318 
01035fb4:  00000000  0007bda4 <runtime.goexit+4>  00b95530  00000000 
01035fc4:  01042040  00000000  00000001  00000001 
01035fd4:  00000000  010000e0  01035fcc  007d979c 
01035fe4:  00000000  00000000  00000002  00000000 
01035ff4:  00000000  00000000  00000000 
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x7bb011, 0x11)
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/panic.go:1116 +0x5c
runtime.gentraceback(0x5d570, 0x1035f58, 0x0, 0x10000e0, 0x0, 0x0, 0x7fffffff, 0x7ea8d8ec, 0x0, 0x0, ...)
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/traceback.go:273 +0x155c
runtime.addOneOpenDeferFrame.func1()
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/panic.go:721 +0x8c
runtime.systemstack(0x79f94)
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/asm_arm.s:347 +0x84
runtime.mstart()
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/proc.go:1116

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/asm_arm.s:294 +0x4 fp=0x1035ed4 sp=0x1035ed0 pc=0x7a09c
runtime.addOneOpenDeferFrame(0x10000e0, 0x5d570, 0x1035f58)
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/panic.go:720 +0x60 fp=0x1035ef0 sp=0x1035ed4 pc=0x4527c
panic(0x770b28, 0xbb06b8)
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/panic.go:929 +0xbc fp=0x1035f58 sp=0x1035ef0 pc=0x45878
runtime.panicmem(...)
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/panic.go:212
runtime.sigpanic()
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/signal_unix.go:742 +0x31c fp=0x1035f70 sp=0x1035f58 pc=0x5d570
runtime: unexpected return pc for runtime.doInit called from 0x0
stack: frame={sp:0x1035f74, fp:0x1035f88} stack=[0x1034000,0x1036000)
01035ef4:  010000e0  0005d570 <runtime.sigpanic+796>  01035f58  01035f44 
01035f04:  0101a360  0100c19c  0001d6a8 <runtime.makemap_small+28>  9cf687f4 
01035f14:  00790820  00000001  0100a400  0101a365 
01035f24:  010000e0  0100a400  0101a360  00056300 <runtime.doInit+136> 
01035f34:  00768890  010000f0  00000000  00770b28 
01035f44:  00bb06b8  00000000  00000000  00000000 
01035f54:  00000000  000562d0 <runtime.doInit+88>  00770b28  00bb06b8 
01035f64:  00000003  000562c4 <runtime.doInit+76>  010000e0  00056300 <runtime.doInit+136> 
01035f74: <00000000  0000001e  000562c4 <runtime.doInit+76>  00b96de0 
01035f84:  01044034 >0102478c  00000012  000562c4 <runtime.doInit+76> 
01035f94:  00b972e0  00048e00 <runtime.main+296>  00000040  00000000 
01035fa4:  00048e94 <runtime.main+444>  00b93f08  00000000  00765318 
01035fb4:  00000000  0007bda4 <runtime.goexit+4>  00b95530  00000000 
01035fc4:  01042040  00000000  00000001  00000001 
01035fd4:  00000000  010000e0  01035fcc  007d979c 
01035fe4:  00000000  00000000  00000002  00000000 
01035ff4:  00000000  00000000  00000000 
runtime.doInit(0x12)
	/media/ware3/Entware.2020.11/build_dir/target-arm_cortex-a9_glibc-2.27_eabi/go-nohf/go-1.15.5/src/runtime/proc.go:5638 +0x58 fp=0x1035f88 sp=0x1035f74 pc=0x562d0

```

**Comment by VA1DER** [comment]
PEBCAK problem.  Issue with device flash.  Closing.
