### ISSUE TITLE
python3-borbackup missing python-packaging dependency

### ISSUE THREAD

**Issue by zyxmon** [Entware/Entware#737]
borg crashes (reported on Qnap forum and confirmed)
```
[/bin] # borg
Traceback (most recent call last):
  File "/opt/bin/borg", line 33, in <module>
    sys.exit(load_entry_point('borgbackup==1.1.17', 'console_scripts', 'borg')())
  File "/opt/bin/borg", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
  File "/opt/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lib/python3.10/site-packages/borg/__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'packaging'
```
A fix should be easy....

**Comment by zyxmon** [comment]
fixed via https://github.com/Entware/rtndev/commit/34be998006a0bd0f58da1abd25840afd9dd072b6
